### ISSUE TITLE
Package does not work

### ISSUE THREAD

**Issue by derwaldgeist** [cedla/meteor-mdi#1]
The fonts are included, but the CSS points to the wrong folder (```../fonts/``` instead of the package folder). To make this work, the fonts would have to be included from ```/packages/cedla_mdi/MaterialDesign-Webfont```.

**Comment by cedla** [comment]
Thanks for the report! I'll correct it ASAP. I think I'll would be better to build the CSS dynamically from the SCSS files, overwriting the `$mdi-font-path` variable.

**Comment by derwaldgeist** [comment]
No problem. Yes, I also think it would be better to build the package based on SASS.

**Comment by cedla** [comment]
Could find some spare time to fix this.
New release available ;)
